<a href="https://colab.research.google.com/github/raven-in-space/data-science-cohort-20/blob/main/Project-3/Project_3_SQL_Analysis_of_Singer_Songwriters.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# SQL Analysis of Singer-Songwriter Sales by Media Type

* **Date:** `5/7/2026`
* **Author:** `Raven Otero-Symphony`

This project was completed as part of the CNM Ingenuity Data Science Bootcamp.

This project uses SQL to investigate the `chinook` music dataset, using a minimum of 13 SQL commands to demonstrate proficiency.

Methods used:

1. `SELECT`
2. `GROUP BY`
3. `ORDER BY`
4. `WHERE`
5. `DISTINCT`
6. `COUNT`
7. `BETWEEN`
8. `AND`
9. `LIMIT`
10. `MAX`
11. `MIN`
12. `SUM`
13. `AVG`

Let's start by importing standard libraries, installing `sqlite`, downloading and unzipping the `chinook` database.

In [2]:
import pandas as pd
import sqlite3 as db
from google.colab import output

In [3]:
# install sqlite package for Ubuntu
%%capture
%%bash
apt-get update
apt-get install -y sqlite3
pip install sqlite-web

In [4]:
# download chinook dataset
%%bash
[ -f chinook.zip ] ||
  curl -s -O https://www.sqlitetutorial.net/wp-content/uploads/2018/03/chinook.zip
unzip -l chinook.zip

Archive:  chinook.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
   884736  2015-11-29 10:53   chinook.db
---------                     -------
   884736                     1 file

In [5]:
# unzip the zipped file
!unzip -u chinook.zip

Archive:  chinook.zip
  inflating: chinook.db

In [6]:
# list all folders in the directory
!ls -la

total 1180
drwxr-xr-x 1 root root   4096 May  8 15:38 .
drwxr-xr-x 1 root root   4096 May  8 14:41 ..
-rw-r--r-- 1 root root 884736 Nov 29  2015 chinook.db
-rw-r--r-- 1 root root 305596 May  8 15:38 chinook.zip
drwxr-xr-x 4 root root   4096 Apr 16 13:28 .config
drwxr-xr-x 1 root root   4096 Apr 16 13:28 sample_data

In [7]:
!ls -lh

total 1.2M
-rw-r--r-- 1 root root 864K Nov 29  2015 chinook.db
-rw-r--r-- 1 root root 299K May  8 15:38 chinook.zip
drwxr-xr-x 1 root root 4.0K Apr 16 13:28 sample_data

In [8]:
# Get a list of the tables in the database
%%script sqlite3 --column --header chinook.db
.tables
;

albums          employees       invoices        playlists
artists         genres          media_types     tracks
customers       invoice_items   playlist_track

In [9]:
# connect the database to a variable for later calling
## recall "db" stands for the sqlite library
db_con = db.connect("chinook.db")

**Question:** How many tables are there? Confirm the data reflects what is shown in the [ERD](https://www.sqlitetutorial.net/sqlite-sample-database/).

In [ ]:
%%script sqlite3 --column --header chinook.db
.tables

albums          employees       invoices        playlists
artists         genres          media_types     tracks
customers       invoice_items   playlist_track

Next, let's take a look at the specific tables.

**Question:** What does the `tracks` database look like?

In [ ]:
%%script sqlite3 --column --header chinook.db
SELECT *
FROM tracks
LIMIT 10
;

TrackId  Name                                     AlbumId  MediaTypeId  GenreId  Composer                                                                Milliseconds  Bytes     UnitPrice
-------  ---------------------------------------  -------  -----------  -------  ----------------------------------------------------------------------  ------------  --------  ---------
1        For Those About To Rock (We Salute You)  1        1            1        Angus Young, Malcolm Young, Brian Johnson                               343719        11170334  0.99
2        Balls to the Wall                        2        2            1                                                                                342562        5510424   0.99
3        Fast As a Shark                          3        2            1        F. Baltes, S. Kaufman, U. Dirkscneider & W. Hoffman                     230619        3990994   0.99
4        Restless and Wild                        3        2            1        F. Baltes, R.A. Smith-Diesel, S. Kaufman, U. Dirkscneider & W. Hoffman  252051        4331779   0.99
5        Princess of the Dawn                     3        2            1        Deaffy & R.A. Smith-Diesel                                              375418        6290521   0.99
6        Put The Finger On You                    1        1            1        Angus Young, Malcolm Young, Brian Johnson                               205662        6713451   0.99
7        Let's Get It Up                          1        1            1        Angus Young, Malcolm Young, Brian Johnson                               233926        7636561   0.99
8        Inject The Venom                         1        1            1        Angus Young, Malcolm Young, Brian Johnson                               210834        6852860   0.99
9        Snowballed                               1        1            1        Angus Young, Malcolm Young, Brian Johnson                               203102        6599424   0.99
10       Evil Walks                               1        1            1        Angus Young, Malcolm Young, Brian Johnson                               263497        8611245   0.99

**Question:** What does the `artists` database look like, and how does it differ from the `tracks` database?

In [ ]:
%%script sqlite3 --column --header chinook.db
SELECT *
FROM artists
limit 10
;

ArtistId  Name
--------  --------------------
1         AC/DC
2         Accept
3         Aerosmith
4         Alanis Morissette
5         Alice In Chains
6         Antônio Carlos Jobim
7         Apocalyptica
8         Audioslave
9         BackBeat
10        Billy Cobham

**Question:** What does the `albums` database look like?

In [ ]:
%%script sqlite3 --column --header chinook.db
SELECT *
FROM albums
LIMIT 10
;

AlbumId  Title                                  ArtistId
-------  -------------------------------------  --------
1        For Those About To Rock We Salute You  1
2        Balls to the Wall                      2
3        Restless and Wild                      2
4        Let There Be Rock                      1
5        Big Ones                               3
6        Jagged Little Pill                     4
7        Facelift                               5
8        Warner 25 Anos                         6
9        Plays Metallica By Four Cellos         7
10       Audioslave                             8

We see that there is a connection between `albums`, `artists`, and `tracks` through the "ArtistId" and "AlbumId" keys.

From `pandas` work earlier (removed to meet the SQL requirement for this project), I noticed that my favorite composer, "Edward Elgar" is listed as a `composer` in the `tracks` database.

In [ ]:
%%script sqlite3 --column --header chinook.db
SELECT *
FROM tracks
WHERE Composer = 'Edward Elgar'
LIMIT 10
;

TrackId  Name                                                                       AlbumId  MediaTypeId  GenreId  Composer      Milliseconds  Bytes    UnitPrice
-------  -------------------------------------------------------------------------  -------  -----------  -------  ------------  ------------  -------  ---------
3421     Nimrod (Adagio) from Variations On an Original Theme, Op. 36 "Enigma"      290      2            24       Edward Elgar  250031        4124707  0.99
3440     Concerto for Cello and Orchestra in E minor, Op. 85: I. Adagio - Moderato  306      2            24       Edward Elgar  483133        7865479  0.99

**Question:** Is Edward Elgar listed as a `Name` in the `artists` database?

In [ ]:
%%script sqlite3 --column --header chinook.db
SELECT *
FROM artists
WHERE Name = 'Edward Elgar'
LIMIT 10
;

We see that Edward Elgar isn't found in the `artists` database. I now hypothesize that, since Elgar is a composer from the 19th-century, only more contemporary artists are listed.

**Question:** Is Michael Jackson listed as a composer in any of his songs?

In [ ]:
%%script sqlite3 --column --header chinook.db
SELECT *
FROM tracks
WHERE Composer = 'Michael Jackson'
LIMIT 10
;

TrackId  Name         AlbumId  MediaTypeId  GenreId  Composer         Milliseconds  Bytes    UnitPrice
-------  -----------  -------  -----------  -------  ---------------  ------------  -------  ---------
3382     Billie Jean  270      2            23       Michael Jackson  281401        4606408  0.99

Let's save the investigation between "Composer" and "Name" for now, and look at another relationship: the `media_types` and `tracks`.

In [ ]:
%%script sqlite3 --column --header chinook.db
SELECT *
FROM media_types
LIMIT 10
;

MediaTypeId  Name
-----------  ---------------------------
1            MPEG audio file
2            Protected AAC audio file
3            Protected MPEG-4 video file
4            Purchased AAC audio file
5            AAC audio file

In [ ]:
%%script sqlite3 --column --header chinook.db
SELECT *
FROM tracks
LIMIT 10
;

TrackId  Name                                     AlbumId  MediaTypeId  GenreId  Composer                                                                Milliseconds  Bytes     UnitPrice
-------  ---------------------------------------  -------  -----------  -------  ----------------------------------------------------------------------  ------------  --------  ---------
1        For Those About To Rock (We Salute You)  1        1            1        Angus Young, Malcolm Young, Brian Johnson                               343719        11170334  0.99
2        Balls to the Wall                        2        2            1                                                                                342562        5510424   0.99
3        Fast As a Shark                          3        2            1        F. Baltes, S. Kaufman, U. Dirkscneider & W. Hoffman                     230619        3990994   0.99
4        Restless and Wild                        3        2            1        F. Baltes, R.A. Smith-Diesel, S. Kaufman, U. Dirkscneider & W. Hoffman  252051        4331779   0.99
5        Princess of the Dawn                     3        2            1        Deaffy & R.A. Smith-Diesel                                              375418        6290521   0.99
6        Put The Finger On You                    1        1            1        Angus Young, Malcolm Young, Brian Johnson                               205662        6713451   0.99
7        Let's Get It Up                          1        1            1        Angus Young, Malcolm Young, Brian Johnson                               233926        7636561   0.99
8        Inject The Venom                         1        1            1        Angus Young, Malcolm Young, Brian Johnson                               210834        6852860   0.99
9        Snowballed                               1        1            1        Angus Young, Malcolm Young, Brian Johnson                               203102        6599424   0.99
10       Evil Walks                               1        1            1        Angus Young, Malcolm Young, Brian Johnson                               263497        8611245   0.99

**Question:** What are the most common `MediaTypeId`'s by `track`?

In [ ]:
%%script sqlite3 --column --header chinook.db
SELECT
  MediaTypeId,
  COUNT(*) AS track_count
FROM tracks
GROUP BY MediaTypeId
ORDER BY track_count DESC
;

MediaTypeId  track_count
-----------  -----------
1            3034
2            237
3            214
5            11
4            7

Interesting...

`MediaTypeId` "1" (or "MPEG audio file") is the most popular choice by far, while "4" (or "Purchased AAC audio file") is the *least* popular.

**Question:** Which songs were purchased as an AAC audio file?

In [ ]:
%%script sqlite3 --column --header chinook.db
SELECT *
FROM tracks
WHERE MediaTypeId = 4
;

TrackId  Name                                                                            AlbumId  MediaTypeId  GenreId  Composer                  Milliseconds  Bytes     UnitPrice
-------  ------------------------------------------------------------------------------  -------  -----------  -------  ------------------------  ------------  --------  ---------
3336     War Pigs                                                                        260      4            23                                 234013        8052374   0.99
3414     Symphony No. 104 in D Major "London": IV. Finale: Spiritoso                     283      4            24       Franz Joseph Haydn        306687        10085867  0.99
3452     SCRIABIN: Prelude in B Major, Op. 11, No. 11                                    318      4            24                                 101293        3819535   0.99
3479     Prometheus Overture, Op. 43                                                     324      4            24       Ludwig van Beethoven      339567        10887931  0.99
3480     Sonata for Solo Violin: IV: Presto                                              325      4            24       Béla Bartók               299350        9785346   0.99
3496     Étude 1, In C Major - Preludio (Presto) - Liszt                                 340      4            24                                 51780         2229617   0.99
3498     Concerto for Violin, Strings and Continuo in G Major, Op. 3, No. 9: I. Allegro  342      4            24       Pietro Antonio Locatelli  493573        16454937  0.99

Somewhat unsurprisingly, symphonic pieces are found here. But what in the world is "War Pigs"?

Let's take a look at the `media_types` inbetween.

**Question:** Which tracks were purchased as protected files?

In [ ]:
%%script sqlite3 --column --header chinook.db
SELECT *
FROM tracks
WHERE MediaTypeId BETWEEN 2 AND 3
;

TrackId  Name                                                                                                           AlbumId  MediaTypeId  GenreId  Composer                                                                                                                                                                                      Milliseconds  Bytes       UnitPrice
-------  -------------------------------------------------------------------------------------------------------------  -------  -----------  -------  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------  ------------  ----------  ---------
2        Balls to the Wall                                                                                              2        2            1                                                                                                                                                                                                      342562        5510424     0.99
3        Fast As a Shark                                                                                                3        2            1        F. Baltes, S. Kaufman, U. Dirkscneider & W. Hoffman                                                                                                                                           230619        3990994     0.99
4        Restless and Wild                                                                                              3        2            1        F. Baltes, R.A. Smith-Diesel, S. Kaufman, U. Dirkscneider & W. Hoffman                                                                                                                        252051        4331779     0.99
5        Princess of the Dawn                                                                                           3        2            1        Deaffy & R.A. Smith-Diesel                                                                                                                                                                    375418        6290521     0.99
1146     Welcome to the Jungle                                                                                          90       2            1                                                                                                                                                                                                      273552        4538451     0.99
1147     It's So Easy                                                                                                   90       2            1                                                                                                                                                                                                      202824        3394019     0.99
1148     Nightrain                                                                                                      90       2            1                                                                                                                                                                                                      268537        4457283     0.99
1149     Out Ta Get Me                                                                                                  90       2            1                                                                                                                                                                                                      263893        4382147     0.99
1150     Mr. Brownstone                                                                                                 90       2            1                                                                                                                                                                                                      228924        3816323     0.99
1151     Paradise City                                                                                                  90       2            1                                                                                                                                                                                                      406347        6687123     0.99
1152     My Michelle                                                                                                    90       2            1                                                                                                                                                                                                      219961        3671299     0.99
1153     Think About You                                                                                                90       2            1                                                                                                                                                                                                      231640        3860275     0.99
1154     Sweet Child O' Mine                                                                                            90       2            1                                                                                                                                                                                                      356424        5879347     0.99
1155     You're Crazy                                                                                                   90       2            1                                                                                                                                                                                                      197135        3301971     0.99
1156     Anything Goes                                                                                                  90       2            1                                                                                                                                                                                                      206400        3451891     0.99
1157     Rocket Queen                                                                                                   90       2            1                                                                                                                                                                                                      375349        6185539     0.99
1158     Right Next Door to Hell                                                                                        91       2            1                                                                                                                                                                                                      182321        3175950     0.99
1159     Dust N' Bones                                                                                                  91       2            1                                                                                                                                                                                                      298374        5053742     0.99
1160     Live and Let Die                                                                                               91       2            1                                                                                                                                                                                                      184016        3203390     0.99
1161     Don't Cry (Original)                                                                                           91       2            1                                                                                                                                                                                                      284744        4833259     0.99
1162     Perfect Crime                                                                                                  91       2            1                                                                                                                                                                                                      143637        2550030     0.99
1163     You Ain't the First                                                                                            91       2            1                                                                                                                                                                                                      156268        2754414     0.99
1164     Bad Obsession                                                                                                  91       2            1                                                                                                                                                                                                      328282        5537678     0.99
1165     Back off Bitch                                                                                                 91       2            1                                                                                                                                                                                                      303436        5135662     0.99
1166     Double Talkin' Jive                                                                                            91       2            1                                                                                                                                                                                                      203637        3520862     0.99
1167     November Rain                                                                                                  91       2            1                                                                                                                                                                                                      537540        8923566     0.99
1168     The Garden                                                                                                     91       2            1                                                                                                                                                                                                      322175        5438862     0.99
1169     Garden of Eden                                                                                                 91       2            1                                                                                                                                                                                                      161539        2839694     0.99
1170     Don't Damn Me                                                                                                  91       2            1                                                                                                                                                                                                      318901        5385886     0.99
1171     Bad Apples                                                                                                     91       2            1                                                                                                                                                                                                      268351        4567966     0.99
1172     Dead Horse                                                                                                     91       2            1                                                                                                                                                                                                      257600        4394014     0.99
1173     Coma                                                                                                           91       2            1                                                                                                                                                                                                      616511        10201342    0.99
1201     Different World                                                                                                94       2            1                                                                                                                                                                                                      258692        4383764     0.99
1202     These Colours Don't Run                                                                                        94       2            1                                                                                                                                                                                                      412152        6883500     0.99
1203     Brighter Than a Thousand Suns                                                                                  94       2            1                                                                                                                                                                                                      526255        8721490     0.99
1204     The Pilgrim                                                                                                    94       2            1                                                                                                                                                                                                      307593        5172144     0.99
1205     The Longest Day                                                                                                94       2            1                                                                                                                                                                                                      467810        7785748     0.99
1206     Out of the Shadows                                                                                             94       2            1                                                                                                                                                                                                      336896        5647303     0.99
1207     The Reincarnation of Benjamin Breeg                                                                            94       2            1                                                                                                                                                                                                      442106        7367736     0.99
1208     For the Greater Good of God                                                                                    94       2            1                                                                                                                                                                                                      564893        9367328     0.99
1209     Lord of Light                                                                                                  94       2            1                                                                                                                                                                                                      444614        7393698     0.99
1210     The Legacy                                                                                                     94       2            1                                                                                                                                                                                                      562966        9314287     0.99
1211     Hallowed Be Thy Name (Live) [Non Album Bonus Track]                                                            94       2            1                                                                                                                                                                                                      431262        7205816     0.99
1496     Surfing with the Alien                                                                                         121      2            1                                                                                                                                                                                                      263707        4418504     0.99
1497     Ice 9                                                                                                          121      2            1                                                                                                                                                                                                      239721        4036215     0.99
1498     Crushing Day                                                                                                   121      2            1                                                                                                                                                                                                      314768        5232158     0.99
1499     Always With Me, Always With You                                                                                121      2            1                                                                                                                                                                                                      202035        3435777     0.99
1500     Satch Boogie                                                                                                   121      2            1                                                                                                                                                                                                      193560        3300654     0.99
1501     Hill of the Skull                                                                                              121      2            1        J. Satriani                                                                                                                                                                                   108435        1944738     0.99
1502     Circles                                                                                                        121      2            1                                                                                                                                                                                                      209071        3548553     0.99
1503     Lords of Karma                                                                                                 121      2            1        J. Satriani                                                                                                                                                                                   288227        4809279     0.99

Let's revisit performers who are also songwriters (that is, musicians listed as both "artists" and "composers").

**Question:** How many unique `Name`'s are there in the `artists` database?

*Functions used:* `DISTINCT`, `ORDER BY`, `SELECT`

In [ ]:
%%script sqlite3 --column --header chinook.db
select DISTINCT name
from artists
ORDER BY name ASC
;

Name
-------------------------------------------------------------------------------------
A Cor Do Som
AC/DC
Aaron Copland & London Symphony Orchestra
Aaron Goldberg
Academy of St. Martin in the Fields & Sir Neville Marriner
Academy of St. Martin in the Fields Chamber Ensemble & Sir Neville Marriner
Academy of St. Martin in the Fields, John Birch, Sir Neville Marriner & Sylvia McNair
Academy of St. Martin in the Fields, Sir Neville Marriner & Thurston Dart
Academy of St. Martin in the Fields, Sir Neville Marriner & William Bennett
Accept
Adrian Leaper & Doreen de Feis
Aerosmith
Aerosmith & Sierra Leone's Refugee Allstars
Aisha Duo
Alanis Morissette
Alberto Turco & Nova Schola Gregoriana
Alice In Chains
Amy Winehouse
Anne-Sophie Mutter, Herbert Von Karajan & Wiener Philharmoniker
Antal Doráti & London Symphony Orchestra
Antônio Carlos Jobim
Apocalyptica
Aquaman
Audioslave
Avril Lavigne
Azymuth
Baby Consuelo
BackBeat
Banda Black Rio
Barry Wordsworth & BBC Concert Orchestra
Barão Vermelho
Battlestar Galactica
Battlestar Galactica (Classic)
Bebel Gilberto
Ben Harper
Berliner Philharmoniker & Hans Rosbaud
Berliner Philharmoniker & Herbert Von Karajan
Berliner Philharmoniker, Claudio Abbado & Sabine Meyer
Big & Rich
Billy Cobham
Black Eyed Peas
Black Label Society
Black Sabbath
Body Count
Boston Symphony Orchestra & Seiji Ozawa
Britten Sinfonia, Ivor Bolton & Lesley Garrett
Bruce Dickinson
Buddy Guy
C. Monteverdi, Nigel Rogers - Chiaroscuro; London Baroque; London Cornett & Sackbu
Caetano Veloso
Cake
Calexico
Charles Dutoit & L'Orchestre Symphonique de Montréal
Charlie Brown Jr.
Chicago Symphony Chorus, Chicago Symphony Orchestra & Sir Georg Solti
Chicago Symphony Orchestra & Fritz Reiner
Chico Buarque
Chico Science & Nação Zumbi
Choir Of Westminster Abbey & Simon Preston
Chor der Wiener Staatsoper, Herbert Von Karajan & Wiener Philharmoniker
Chris Cornell
Christina Aguilera featuring BigElf
Christopher O'Riley
Cidade Negra
Cláudio Zoli
Corinne Bailey Rae
Creedence Clearwater Revival
Cássia Eller
DJ Dolores & Orchestra Santa Massa
David Coverdale
Deep Purple
Def Leppard
Dennis Chambers
Dhani Harrison & Jakob Dylan
Djavan
Dread Zeppelin
Ed Motta
Edo de Waart & San Francisco Symphony
Edson, DJ Marky & DJ Patife Featuring Fernanda Porto
Elis Regina
Emanuel Ax, Eugene Ormandy & Philadelphia Orchestra
Emerson String Quartet
English Concert & Trevor Pinnock
Equale Brass Ensemble, John Eliot Gardiner & Munich Monteverdi Orchestra and Choir
Eric Clapton
Eugene Ormandy
Faith No More
Falamansa
Felix Schmidt, London Symphony Orchestra & Rafael Frühbeck de Burgos
Fernanda Porto
Foo Fighters
Frank Sinatra
Frank Zappa & Captain Beefheart
Fretwork
Funk Como Le Gusta
Gene Krupa
Gerald Moore
Gilberto Gil
Godsmack
Gonzaguinha
Green Day
Guns N' Roses
Gustav Mahler
Gustavo & Andres Veiga & Salazar
Göteborgs Symfoniker & Neeme Järvi
Habib Koité and Bamada
Herbert Von Karajan, Mirella Freni & Wiener Philharmoniker
Hermeto Pascoal
Heroes
Hilary Hahn, Jeffrey Kahane, Los Angeles Chamber Orchestra & Margaret Batjer
House Of Pain
Incognito
Instituto
Iron Maiden
Itzhak Perlman
JET
Jack Johnson
Jack's Mannequin & Mick Fleetwood
Jackson Browne
Jaguares
James Brown
James Levine
Jamiroquai
Jimi Hendrix
Joe Satriani
Jorge Ben
Jorge Vercilo
Jota Quest
João Gilberto
João Suplicy
Judas Priest
Julian Bream
Karsh Kale
Kent Nagano and Orchestre de l'Opéra de Lyon
Kid Abelha
Kiss
Led Zeppelin
Legião Urbana
Lenny Kravitz
Leonard Bernstein & New York Philharmonic
Les Arts Florissants & William Christie
London Symphony Orchestra & Sir Charles Mackerras
Los Hermanos
Los Lonely Boys
Lost
Luciana Souza/Romero Lubambo
Luciano Pavarotti
Luiz Melodia
Lulu Santos
Marcos Valle
Marillion
Marisa Monte
Martin Roscoe
Marvin Gaye
Matisyahu
Maurizio Pollini
Mela Tenenbaum, Pro Musica Prague & Richard Kapp
Men At Work
Metallica
Michael Tilson Thomas & San Francisco Symphony
Michele Campanella
Miles Davis
Milton Nascimento
Milton Nascimento & Bebeto
Motörhead
Motörhead & Girlschool
Mundo Livre S/A
Mônica Marianno
Mötley Crüe
Nando Reis
Nash Ensemble
Nação Zumbi
Nega Gizza
Ney Matogrosso
Nicolaus Esterhazy Sinfonia
Nirvana
O Rappa
O Terço
Olodum
Orchestra of The Age of Enlightenment
Orchestre Révolutionnaire et Romantique & John Eliot Gardiner
Os Cariocas
Os Mutantes
Os Paralamas Do Sucesso
Otto
Otto Klemperer & Philharmonia Orchestra
Ozzy Osbourne
Page & Plant
Passengers
Paul D'Ianno
Pearl Jam
Pedro Luís & A Parede
Pedro Luís E A Parede
Peter Tosh
Philharmonia Orchestra & Sir Neville Marriner
Philip Glass Ensemble
Pink Floyd
Planet Hemp
Queen
R.E.M.
R.E.M. Feat. KRS-One
R.E.M. Feat. Kate Pearson
Raimundos
Raul Seixas
Red Hot Chili Peppers
Regina Spektor
Richard Marlow & The Choir of Trinity College, Cambridge
Rodox
Roger Norrington, London Classical Players
Royal Philharmonic Orchestra & Sir Thomas Beecham
Rush
Sabotage E Instituto
Sandra De Sá
Santana
Santana Feat. Dave Matthews
Santana Feat. Eagle-Eye Cherry
Santana Feat. Eric Clapton
Santana Feat. Everlast
Santana Feat. Lauryn Hill & Cee-Lo
Santana Feat. Maná
Santana Feat. Rob Thomas
Santana Feat. The Project G&B
Scholars Baroque Ensemble
Scorpions
Sergei Prokofiev & Yuri Temirkanov
Seu Jorge
Simply Red
Sir Georg Solti & Wiener Philharmoniker
Sir Georg Solti, Sumi Jo & Wiener Philharmoniker
Skank
Smashing Pumpkins
Snow Patrol
Soundgarden
Spyro Gyra
Stereo Maracana
Stevie Ray Vaughan & Double Trouble
Stone Temple Pilots
System Of A Down
Temple of the Dog
Terry Bozzio, Tony Levin & Steve Stevens
The 12 Cellists of The Berlin Philharmonic
The Black Crowes
The Clash
The Cult
The Doors
The Flaming Lips
The King's Singers
The Office
The Police
The Posies
The Postal Service
The Rolling Stones
The Tea Party
The Who
Tim Maia
Titãs
Ton Koopman
Toquinho & Vinícius
U2
UB40
Van Halen
Various Artists
Velvet Revolver
Vinicius, Toquinho & Quarteto Em Cy
Vinícius De Moraes
Vinícius De Moraes & Baden Powell
Vinícius E Odette Lara
Vinícius E Qurteto Em Cy
Whitesnake
Wilhelm Kempff
Xis
Yehudi Menuhin
Yo-Yo Ma
Youssou N'Dour
Zeca Pagodinho

Here, we find there are 275 unique artists listed.

In [ ]:
%%script sqlite3 --column --header chinook.db
SELECT DISTINCT COUNT(name)
FROM artists
;

COUNT(name)
-----------
275

*However*... this is not completely accurate. We can see from the listed query that artists contain special characters such as `-;&ö` and others.

Let's take a look at the "Composers" to prove this point.

In [ ]:
%%script sqlite3 --column --header chinook.db
SELECT DISTINCT composer
FROM tracks
ORDER BY composer ASC
;

Composer
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

A. F. Iommi, W. Ward, T. Butler, J. Osbourne
A. Jamal
A.Bouchard/J.Bouchard/S.Pearlman
A.Isbell/A.Jones/O.Redding
AC/DC
Aaron Copland
Aaron Goldberg
Ace Frehley
Acyi Marques/Arlindo Bruz/Braço, Beto Sem/Zeca Pagodinho
Acyr Marques/Arlindo Cruz/Franco
Adalto Magalha/Lourenco
Adam Clayton, Bono, Larry Mullen & The Edge
Adam Clayton, Bono, Larry Mullen, The Edge
Addie William Jones/Nat Jones
Adrian Smith
Adrian Smith/Bruce Dickinson
Adrian Smith/Bruce Dickinson/Nicko McBrain
Adrian Smith/Bruce Dickinson/Steve Harris
Adrian Smith/Clive Burr/Steve Harris
Adrian Smith/Steve Harris
Adrian Smith; Bruce Dickinson
Adrian Smith; Bruce Dickinson; Steve Harris
Adrian Vanderberg/David Coverdale
Adriano Bernandes/Edmar Neves
Al Cleveland/Marvin Gaye/Renaldo Benson
Al Perkins/Willie Dixon
Alanis Morissette & Glenn Ballard
Alba Carvalho/Fernando Porto
Albert King
Alcides Dias Lopes
Alcino Corrêa/Monarco
Aldir Blanc/Jayme Vignoli
Alex North/Hy Zaret
Alex Van Halen/David Lee Roth/Edward Van Halen/Michael Anthony
Alexandre Brazil/Pedro Luis/Rodrigo Cabelo
Alfred Ellis/James Brown
Allen Story/George Gordy/Robert Gordy
Almir Guineto/Dedé Paraiso/Luverci Ernesto
Amos Blakemore/Buddy Guy
Andrea Dulbecco
Angus Young, Malcolm Young, Brian Johnson
Anonymous
Anthony Kiedis, Flea, John Frusciante, and Chad Smith
Anthony Kiedis/Chad Smith/Flea/John Frusciante
Antonio Carlos Jobim
Antonio Carlos Jobim/Vinicius de Moraes
Antonio Lopes
Antonio Vivaldi
Apocalyptica
Arlindo Cruz/Carlos Sena/Elmo Caetano/Mauricao
Arlindo Cruz/Franco/Marquinhos PQD/Negro, Jovelina Pérolo/Zeca Pagodinho
Arnaldo Antunes
Arnaldo Antunes/Britto, SergioMiklos, Paulo
Arnaldo Antunes/Charles Gavin/Marcelo Fromer/Sérgio Britto/Toni Bellotto
Arnaldo Anutnes/Branco Mello/Marcelo Fromer/Sergio Brotto/Toni Bellotto
Arnaldo Anutnes/Marcelo Fromer/Paulo Miklos
Arnaldo Baptista - Rita Lee
Arnaldo Baptista - Rita Lee -  Sérgio Dias
Arnaldo Baptista - Rita Lee - Arnolpho Lima Filho
Arnaldo Baptista - Rita Lee - Sérgio Dias
Arnaldo Baptista/Rita Lee/Sérgio Dias
Arthur Crudup/Bernard Besman/Bukka White/Doc Pomus/John Bonham/John Lee Hooker/John Paul Jones/Mort Shuman/Robert Plant/Willie Dixon
Astor Campbell, Delroy "Chris" Cooper, Donovan Jackson, Dorothy Fields, Earl Chinna Smith, Felix Howard, Gordon Williams, James Moody, Jimmy McHugh, Matt Rowe, Salaam Remi & Stefan Skarbek
Astor Piazzolla
Audioslave/Chris Cornell
Augusto Conceição/Chiclete Com Banana
Augusto Garcez/Nelson Cavaquinho
Augusto/Craig Negoescu/Rocco Filho/Saara, Ze Carlos Da
B. Carter/C. Layton/R. Ellsworth/R. Wynans/T. Shannon
B. Cummings/G. Peterson/M.J. Kale/R. Bachman
B. Daisley, O. Osbourne & R. Rhoads
B. Guy
B. de Filippi - F. Migliaci - Versão: Fred Jorge
Baden Powell/Vinicius de Moraes
Bahiano/Chuck Rio/Diego Blanco/Herbert Vianna
Bahiano/Diego Blanco/Herbert Vianna
Barrett Strong/Norman Whitfield
Barrett Strong/Norman Whitfield/Roger Penzabene
Ben E.King/James Bethea
Ben Shepherd/Chris Cornell
Ben Shepherd/Chris Cornell/Kim Thayil/Matt Cameron
Bernardo Vilhena/Bino Farias/Da Gama/Lazão/Toni Garrido
Bernardo Vilhena/Bino/Da Gama/Lazao/Toni Garrido
Bernardo Vilhena/Da Gama/Lazao
Bernardo Vilhena/Da Gama/Lazão
Berry Gordy, Jr./Janie Bradford
Bert Russell/Phil Medley
Beto Gogo/Jessé Pai/Luiz Carlos/Zeca Pagodinho
Beto Guedes, Márcio Borges
Beto Guedes, Ronaldo Bastos
Beto Guedes/Fernando Brant/L Borges
Betty Newsome/James Brown
Bi Ribeira/Herbert Vianna/João Barone
Bi Ribeiro/Herbert Vianna/João Barone
Big Bill Broonzy
Bill Berry-Peter Buck-Mike Mills-Michael Stipe
Bill Berry/Michael Stipe/Mike Mills/Peter Buck
Bill Dees/Roy Orbison
Bill Gould/Jon Hudson/Mike Bordin/Mike Patton
Bill Gould/Jon Hudson/Mike Bordin/Mike Patton/Roddy Bottum
Bill Gould/Mike Bordin/Mike Patton
Bill Gould/Mike Patton
Billie Joe Armstrong -Words Green Day -Music
Billie Joe Armstrong, Mike Dirnt, Tré Cool
Billie Joe Armstrong/Green Day
Billy Cobham
Billy Corgan
Billy Duffy/Bob Rock/Ian Astbury
Billy Duffy/Ian Astbury
Billy Duffy/Ian Astbury/Marti Frederiksen/Mick Jones
Billy Roberts
Billy/Del James/W. Axl Rose/West Arkeen
Bino Farias/Da Gama/Henry Lawes/Lazão/Toni Garrido/Winston Foser-Vers
Bino Farias/Da Gama/Lazão/Pedro Luis/Toni Garrido
Bino Farias/Da Gama/Lazão/Rás Bernardo
Bino Farias/Da Gama/Lazão/Toni Garrido
Bino Farias/Da Gamma/Lazão/Rás Bernard
Bino/Da Gama/Lazao/Ras Bernardo
Bino/Da Gama/Ras Bernardo
Bino/Da Gama/Toni Garrido
Bino/Da Gamma/Lazao/Toni Garrido
Bizuca/Clóvis Pê/Gilson Bernini/Marelo D'Aguia
Black Sabbath
Blackmore, Gillan, Glover, Lord, Paice
Blackmore, Glover, Turner
Blackmore, Glover, Turner, Lord, Paice
Blackmore/Coverdale
Blackmore/Coverdale/Lord/Paice
Blackmore/Gillan/Glover/Lord/Paice
Blaze Bayley/David Murray/Steve Harris
Blaze Bayley/Janick Gers
Blaze Bayley/Janick Gers/Steve Harris
Blaze Bayley/Steve Harris
Bo Diddley
Bob Cochran/Sharon Sheeley
Bob Dylan
Bob Rock/James Hetfield/Kirk Hammett/Lars Ulrich
Bobby Byrd/James Brown/Ron Lenhoff
Bolin/Coverdale
Bolin/Coverdale/Paice
Bolin/Hughes
Bolin/Hughes/Lord
Bombom/Ed Motta
Bono
Bono, The Edge, Adam Clayton, and Larry Mullen
Bono/Clayton, Adam/Dylan, Bob/Mullen Jr., Larry/The Edge
Bono/Clayton, Adam/Mullen Jr., Larry/The Edge
Bossi/David Coverdale/Earl Slick
Bourge/Phillips/Shelley
Brad Shapiro/George Jackson/Robert Miller/Walter Shaw
Branco Mello/Carlos Barmack/Ciro Pessoa/Marcelo Fromer/Toni Belloto
Brian Eno, Bono, Adam Clayton, The Edge & Larry Mullen Jnr.
Brian Eno/U2
Brian Holland/Eddie Holland/Lamont Dozier
Brian Holland/Freddie Gorman/Georgia Dobbins/Robert Bateman/William Garrett
Brian May
Bruce Dickinson
Bruce Dickinson/David Murray
Bruce Dickinson/David Murray/Steve Harris
Bruce Dickinson/Janick Gers
Bruce Dickinson/Janick Gers/Steve Harris
Bruce Dickinson/Steve Harris
Bruce Dickinson; Harris
Bruce/Clapton
Bryan Adams/Nikki Sixx/Scott Humphrey
Buchanan, Wallis
Buddy Guy
Buzz Cason/Mac Gayden
Béla Bartók
C. A./C.A./Celso Alvim/Herbert Vianna/Mário Moura/Pedro Luís/Sidon Silva
C. Burnett
C. Cester
C. Cester/C. Muncey
C. Cester/C. Muncey/N. Cester
C. Cester/N. Cester
C. Muncey/N. Cester
C.Burton
Caetano Veloso
Caetano Veloso - Djavan
Caetano Veloso - Gilberto Gil
Caetano Veloso - Waly Salomão
Caetano Veloso e Gilberto Gil
Cal Adan/Del Rey, Tension/Edu Casanova
Cal Adan/Ferrugem/Julinho Carioca/Tríona Ní Dhomhnaill
Cal Adan/Paulo Levi
Cale/Clapton
Carl Nielsen
Carl Orff
Carlinhos Brown
Carlinhos Brown/Herbert Vianna
Carlinhos Santana/Nelson Rufino
Carlos Imperial/Edardo Araújo
Carlos Imperial/Tim Maia
Carlos Santana
Carlos Santana & C. Thompson
Carlos Santana & Dave Matthews
Carlos Santana & KC Porter
Carlos Santos/Ciro/Claudio Russo/Zé Luiz
Carolyn Franklin and Sonny Saunders
Caruso/Cleber/Deo/Osmar
Cassiano Costa/Cintia Maviane/J.F./Lucas Costa
Cave
Charles Bobbitt/James Brown
Charles Gavin/Marcelo Fromer/Sérgio Britto
Charlie Midnight/Dan Hartman
Chester Burnett/Jimmy Page/John Bonham/John Paul Jones/Robert Plant
Chet Catallo
Chico Amaral/Edgard Scandurra/Samuel Rosa
Chico Amaral/Lelo Zanettik
Chico Amaral/Samuel Rosa
Chico Buarque
Chico Science
Chico Science/Dengue/Lúcio Maia
Chris Cornell
Chris Cornell/Kim Thayil
Chris Frantz/David Byrne/Jerry Harrison/Tina Weymouth
Chris Robinson/Rich Robinson
Chuck Berry
Cidade Negra
Ciro Pressoa/Marcelo Fromer
Clapton
Clapton/Collins/Pappalardi
Clapton/Dylan
Clapton/F.eldman/Linn
Clapton/Gordon
Clapton/Harrison
Clapton/J. J. Cale
Clapton/Levy
Clapton/Robert Johnson Arr: Eric Clapton
Clapton/Trad. Arr. Clapton
Clarke/Farren/Kilmister/Tayler
Clarke/Kilmister/Tayler
Clarke/Kilmister/Taylor
Claudio Martins/David Lima/Kleber Rodrigues/Livre, Cesare Som
Claudio Monteverdi
Cliff Burton
Collins/Van Zandt
Cook/Coverdale
Cornell, Commerford, Morello, Wilk
Corumbá/José Gumarães/Venancio
Coverdale
Coverdale/Hughes
Coverdale/Hughes/Lord/Paice
Coverdale/Lord/Paice
Craig Ross/Lenny Kravitz
Cub Coda/Michael Lutz
Culmer/Exalt
D. DeLeo/Kretz/R. DeLeo/Weiland
D. DeLeo/Kretz/Weiland
D. DeLeo/R. DeLeo/Weiland
D.Coverdal/G.Hughes/Glenn Hughes/I.Paice/Ian Paice/J.Lord/John Lord
D.Coverdale/G.Hughes/Glenn Hughes/I.Paice/Ian Paice/J.Lord/John Lord/R.Blackmore/Ritchie Blackmore
D.Coverdale/G.Hughes/Glenn Hughes/J.Lord/John Lord
D.Coverdale/G.Hughes/Glenn Hughes/R.Blackmore/Ritchie Blackmore
D.Coverdale/R.Blackmore/Ritchie Blackmore
Da Gama/Lazao/Toni Garrido
Da Gama/Lazão/Rás Bernardo
Da Gama/Toni Garrido
Dadinho/Gilbreto Gomes/Gustavo/P.C. Portugal/R. Mocoto
Dado Villa-Lobos
Dado Villa-Lobos/Ico Ouro-Preto/Marcelo Bonfá
Dado Villa-Lobos/Marcelo Bonfá
Dale Evans
Daniel Lanois
Danzig
Darius "Take One" Minwalla/Jon Auer/Ken Stringfellow/Matt Harris
Dave Abbruzzese & Jeff Ament & Stone Gossard & Mike McCready & Eddie Vedder
Dave Abbruzzese/Eddie Vedder/Jeff Ament/Mike McCready/Stone Gossard
Dave Brubeck
Dave Grohl
Dave Grohl, Taylor Hawkins, Nate Mendel, Chris Shiflett
Dave Grohl, Taylor Hawkins, Nate Mendel, Chris Shiflett/FOO FIGHTERS
Dave Krusen/Stone Gossard
Dave Kushner, Duff, Keith Nelson, Matt Sorum, Scott Weiland & Slash
Dave Kushner, Duff, Matt Sorum, Scott Weiland & Slash
Dave Murray; Steve Harris
Dave, Taylor, Nate, Chris
David Cook
David Corrêa - Paulinho Carvalho - Carlos Sena - Bira do Ponto
David Coverdale
David Coverdale/Earl Slick
David Murray/Paul Di'Anno/Steve Harris
David Murray/Steve Harris
De Beauport/Jagger/Richards
Deacon
Deacon, John
Deacon, John/May, Brian
Deacon/May/Mercury/Taylor
Deaffy & R.A. Smith-Diesel
Dean Brown, Dennis Chambers & Jim Beard
Dean Deleo
Deanna Brown/Deidra Jenkins/Yamma Brown
Delroy "Chris" Cooper, Donovan Jackson, Earl Chinna Smith, Felix Howard, Gordon Williams, Luke Smith, Paul Watson & Wilburn Squiddley Cole
Derrick McKenzie/Jay Kay/Toby Smith
Diamond/Shermann
Dick Holler
Dickinson
Dickinson/Smith
Dito/Djalma Falcao/Ilha, Almir Da/Márcio André
Di´Anno/Harris
Djavan
Djavan - Gabriel, O Pensador
Do Vale, João/Luiz Wanderley
Do Vale, Valverde/Gal Oliveira/Luciano Pinto
Dolmayan, John/Malakian, Daron/Odadjian, Shavo
Dolores Duran
Domenil/J. Brito/Joaozinho/Rap, Marcelo Do
Dominguinhos/Gilberto Gil
Don Van Vliet
Donato/Gilberto Gil
Douglas/Neves, Vicente Das/Silva, Gilmar L./Toninho Gentil/Wantuir
Doyle Bramhall/Stevie Ray Vaughan
Dudu Nobre
Dudu Nobre/Zeca Pagodinho
Duff McKagan
Duff McKagan/Slash/W. Axl Rose
Dufort/Johnson/McAuliffe/Williams
Dylan, Bob
E. Schrody/J. Vasquez/L. Dimant
E. Schrody/L. Dimant
E. Schrody/L. Dimant/L. Muggerud
E. Schrody/L. Freese/L. Muggerud
E. Schrody/L. Muggerud
E. Schrody/L. Muggerud/R. Medrano
E. Schrody/R. Medrano
E. Shrody
E.Weiss
Eale-Eye Cherry, M. Simpson, J. King & M. Nishita
Eddie Casillas/Roy Z
Eddie Cochran/Jerry Capehart
Eddie Vedder
Eddie Vedder & Mike McCready
Eddie Vedder & Stone Gossard
Eddie Vedder/Jeff Ament/Matt Cameron/Mike McCready/Stone Gossard
Edvard Grieg
Edward Elgar
Edward Van Halen, Alex Van Halen, David Lee Roth
Edward Van Halen, Alex Van Halen, David Lee Roth, Michael Anthony
Edward Van Halen, Alex Van Halen, Michael Anthony and David Lee Roth
Edward Van Halen, Alex Van Halen, Michael Anthony,/Edward Van Halen, Alex Van Halen, Michael Anthony, David Lee Roth
Edward Van Halen, Alex Van Halen, Michael Anthony,/Edward Van Halen, Alex Van Halen, Michael Anthony, Sammy Hagar
Emerson Villani
Enotris Johnson/Little Richard/Robert "Bumps" Blackwell
Erasmo Carlos/Roberto Carlos
Eric Clapton
Eric Clapton, Jim Gordon
Eric Clapton, Robert Cray
Eric Clapton, Will Jennings
Erik Satie
Eugene McDaniel
Eurreal Montgomery
F. Baltes, R.A. Smith-Diesel, S. Kaufman, U. Dirkscneider & W. Hoffman
F. Baltes, S. Kaufman, U. Dirkscneider & W. Hoffman
F. Olivera
Faith No More
Faithfull/Jagger/Richards
Fausto Fawcett/Samuel Rosa
Fausto Nilo - Armandinho
Fausto Nilo/Moraes Moreira/Pepeu Gomes
Fayyaz Virgi/Richard Bull
Fito Paez/Herbert Vianna
Flavio Bororo/Paulo Apparicio/Wagner Alves/Zeca Sereno
Folclore
Foo Fighters
Frank Zappa
Franz Joseph Haydn
Franz Schubert
Fred Wesley/James Brown
Fred Wesley/James Brown/Joseph Mims
Freddie Mercury
Freddie Mercury & John Deacon
Freddy James, Jimmy hogarth & Larry Stock
Frédéric Chopin
Full Force/James Brown
Fábio Nolasco/Gal Sales/Ivan Brasil
G Harvey/R Hope-Taylor
G M Sumner
Gabriel Fauré
Galley
Garay, Ricardo Engels/Luca Predabom/Ludwig, Carlos Henrique/Maurício Vieira
Geddy Lee And Alex Lifeson/Geddy Lee And Neil Peart/Rush
Gelder, Nick van
Gene Simmons
Gene Simmons, S. Coronel
Gene Simmons, Stephen Coronel
Genival Cassiano
Genival Cassiano/Silvio Rochael
George Duke
George Frideric Handel
Georges Bizet
Gerry DeVeaux/Terry Britten
Giacomo Puccini
Gil Evans
Gilberto Gil
Gilberto Gil - Caetano Veloso
Gillan/Glover/Lord/Nix - Blackmore/Paice
Gillan/Glover/Lord/Paice
Gilmour, Mason, Wright, Waters
Gilmour, Waters
Gilson Mendonça/Michel
Giovanni Pierluigi da Palestrina
Giuseppe Verdi
Gonzaga Jr
Gonzaga Jr.
Gonzaga Jr/Gonzaguinha
Gonzaguinha
Graham Harvey
Grazielle/Roque Ferreira
Green Day
Greg Macainsh
Gregorio Allegri
Guga/Marquinho Lessa/Tuninho Professor
Guio De Morais E Seus "Parentes"/Luiz Gonzaga
Gule/Jorge 101/Lequinho/Luiz Piao
Gustav Holst
Gustav Mahler
H. Spina, J. Elliott
Habib Koité
Harris
Harris/Di Anno
Harris/Paul Di´Anno
Harris/Tatler
Harry Lawes/Winston Foster-Vers
Hawkins-Lewis-Broadwater
Heath/Robinson
Hector Berlioz
Hendrix, Jimi
Henry Hirsch/Lenny Kravitz
Henry Kirssch/Lenny Kravitz/S. Pasch A. Krizan
Henry Purcell
Henryk Górecki
Herbert Vianna
Herbert Vianna/Paulo Sérgio Valle
Herbert Vianna/Tet Tillett
Herbert Vianna/Tetê Tillet
Hetfield, Ulrich
Hetfield, Ulrich, Hammett
Hetfield, Ulrich, Newsted
Holocaust
Humberto Teixeira/Luiz Gonzaga
Hyldon
I. Toure, S. Tidiane Toure, Carlos Santana & K. Perazzo
Ian Gillan, Roger Glover, Jon Lord, Steve Morse, Ian Paice
Ian Gillan/Ian Paice/Jon Lord/Ritchie Blckmore/Roger Glover
Ian Stewart/John Bonham/John Paul Jones/Mrs. Valens/Robert Plant
Igor Stravinsky
Ira Gershwin, Kurt Weill
Isham Jones & Marty Symes
Ivan Kral/Patti Smith
Ivy Hunter/Stevie Wonder
Ivy Hunter/William "Mickey" Stevenson
Ivy Jo Hunter/Marvin Gaye/William Stevenson
Izzy Stradlin'
Izzy Stradlin'/W. Axl Rose
J B Lenoir/Willie Dixon
J. B. Lenoir/Willie Dixon
J. C. Fogerty
J. Carisi
J. Kay/Jay Kay
J. Purdell, M. Inez, O. Osbourne, R. Castillo & Z. Wylde
J. Satriani
J.C. Fogerty
J.Hetfield/L.Ulrich
J.J. Johnson
J.J. Johnson/R. Troup, L. Worth
J.r.Bertami/Parana
Jack Yellen/Milton Ager
Jagger/Richards
Jagger/Richards/Oldham
James Brown
James Brown & Bobby Byrd
James Brown/Johnny Terry
James Brown/Tim Maia
James Hetfield
James Hetfield & Lars Ulrich
James Hetfield and Lars Ulrich
James Hetfield, Lars Ulrich
James Hetfield, Lars Ulrich & Jason Newsted
James Hetfield, Lars Ulrich & Kirk Hammett
James Hetfield, Lars Ulrich and Cliff Burton
James Hetfield, Lars Ulrich and Jason Newsted
James Hetfield, Lars Ulrich and Kirk Hammett
James Hetfield, Lars Ulrich, Dave Mustaine
James Hetfield, Lars Ulrich, Kirk Hammett
James Iha
Janick Gers/Steve Harris
Jauperi/Zeu Góes
Jay Beckenstein
Jay Hawkins
Jay Kay
Jay Kay/Kay, Jay
Jay Kay/Toby Smith
Jean Paul Maunick
Jean Sibelius
Jeff Ament
Jeff Ament & Eddie Vedder
Jeff Ament & Stone Gossard & Jack Irons & Mike McCready & Eddie Vedder
Jeff Ament/Mike McCready/Stone Gossard
Jeff Ament/Stone Gossard
Jeremy Wall
Jerry Cantrell
Jerry Cantrell, Layne Staley
Jerry Cantrell, Michael Starr, Layne Staley
Jerry Cantrell, Michael Starr, Sean Kinney
Jerry Lynn Williams
Jerry Ragavoy
Jesse Ed Davis III/Taj Mahal
Jesse Fuller
Jim Beard
Jim Beard & Jon Herington
Jimi Hendrix
Jimmy Cox
Jimmy Forrest/Lewis C. Simpkins/Oscar Washington
Jimmy Page
Jimmy Page & Robert Plant
Jimmy Page, Robert Plant
Jimmy Page, Robert Plant & John Paul Jones
Jimmy Page, Robert Plant, Charlie Jones, Michael Lee
Jimmy Page, Robert Plant, John Bonham
Jimmy Page, Robert Plant, John Bonham, John Paul Jones
Jimmy Page, Robert Plant, John Paul Jones
Jimmy Page, Robert Plant, John Paul Jones, John Bonham
Jimmy Page, Robert Plant, John Paul Jones, John Bonham, Memphis Minnie
Jimmy Page/Jimmy Page & Robert Plant/Robert Plant
Jimmy Page/John Bonham/John Estes/John Paul Jones/Robert Plant
Jimmy Page/John Bonham/John Paul Jones
Jimmy Page/John Bonham/John Paul Jones/Robert Plant/Willie Dixon
Jimmy Page/John Paul Jones
Jimmy Page/Led Zeppelin
Jimmy Page/Robert Johnson/Robert Plant
Jimmy Page/Robert Plant
Jimmy and Vella Cameron
Joe Strummer/Mick Jones
Johann Pachelbel
Johann Sebastian Bach
Johann Strauss II
John Adams
John Bonham
John Bonham, John Paul Jones, Jimmy Page
John Bonham/John Paul Jones
John Bonham/John Paul Jones/Robert Plant
John Bonham/John Paul Jones/Robert Plant/Willie Dixon
John Brim
John Deacon
John Dowland
John Entwistle
John Entwistle/Pete Townshend
John Lennon, Paul McCartney
John Paul Jones
John Paul Jones & Robert Plant
John Paul Jones, Jimmy Page & Robert Plant
John Paul Jones/Robert Plant
John Scofield
John Scofield, Robert Aries, Milton Chambers and Gary Grainger
John and William Valentine
Jon Herington
Jon Hudson/Mike Bordin/Mike Patton
Jon Hudson/Mike Patton
Jones/Sirotto/Smith
Jorge Aragão/Zeca Pagodinho
Jorge Ben
Jorge Cardoso/Pierre Onasis
Jorge Vercilo/Jota Maranhao
João Suplicy
Julian Crampton
K.Hammett
KC Porter & JB Eckl
Karol Szymanowski
Karsh Kale
Karsh Kale/Vishal Vaid
Keith Richards/Mick Jagger
Kelly, Mosley, Rothery, Trewaves
Kenny Gamble and Leon Huff
Kevin Robinson
Kevin Robinson/Richard Bull
Killing Joke
Kretz/R. DeLeo/Weiland
Kurt Cobain
Kurt Weill
L. Delibes
L. Hill
L. Kerslake, O. Osbourne, R. Daisley & R. Rhoads
L. Kilmister, O. Osbourne & Z. Wylde
L. Muggerud
Larry Williams
Lennon, John/McCartney, Paul
Lenny Kravitz
Lenny Kravitz/Slash
Leão, Rodrigo F./Lô Borges/Samuel Rosa
Leão, Rodrigo F./Samuel Rosa
Little Richard
Lowman Pauling
Luca Gusella
Luciana Souza
Lucina/Luli
Ludwig van Beethoven
Luiz Carlos/Oberdan
Luiz Gonzaga/Zé Dantas
Luiz Melodia/Ricardo Augusto
Luiz Wanderley/Paulo Levi
Luke Smith
Lulu Santos
Lô Borges, Fernando Brant
Lô Borges, Márcio Borges, Fernando Brant
M. Itaal Shur & Rob Thomas
M.Babatunde Olantunji
Mabins, Macie/Magee, Sterling/Robinson, Bobby
Macelo Yuka/O Rappa
Manuca/Raimundinho DoAcordion/Targino Godim
Marc-Antoine Charpentier
Marco Tulio Lara/Rogerio Flausino
Marcos Valle
Marisa Monte/Nando Reis
Marisa Monte/poema de Octavio Paz/versão: Haroldo de Campos
Mark Ronson
Marley
Marsden
Marsden/Moody
Marvin Gaye
Mason, Waters, Wright, Gilmour
Mason/Waters, Gilmour, Wright
Matt Cameron
Matt Cameron & Mike McCready
Matt Rowe & Stefan Skarbek
Mauro Diniz/Ratino Sigem
Maxton Gig Beesley Jnr.
May
May, Brian
McKinley Morgenfield (Muddy Waters)
Mercury
Mercury, Freddie
Metallica
Michael Jackson
Mick Hucknall
Mick Hucknall and Fritz McIntyre
Mick Hucknall and Lamont Dozier
Mick Hucknall and Neil Moss
Mick Jagger, Keith Richard
Mick Jones/Traditional arr. Joe Strummer
Mick Mars/Nikki Sixx
Mick Mars/Nikki Sixx/Tommy Lee
Mick Mars/Nikki Sixx/Tommy Lee/Vince Neil
Mike Bordin, Billy Gould, Mike Patton
Mike Bordin, Billy Gould, Mike Patton, Trey Spruance
Mike Dint, Billie Joe, Tré Cool
Mike Dirnt -Words Green Day -Music
Mike Dirnt/Tré Cool
Mike McCready
Mike McCready & Stone Gossard
Mike Patton
Miles Davis
Miles Davis, Gil Evans
Milton Nascimento
Milton Nascimento, Caetano Veloso
Milton Nascimento, Fernando Brant
Milton Nascimento, Márcio Borges
Milton Nascimento, Ronaldo Bastos
Molaney/Morris/Roberts/Wainwright
Moody
Morais
Murilão
Murray  Dave
Mutantes
Mônica Marianno
N. Cester
Nando Reis
Nando Reis/Samuel Rosa
Nanker Phelge
Ned Fairchild
Nei Lopes/Wilson Moreira
Neil Young
Nelson Angelo
Niccolò Paganini
Nickolas Ashford & Valerie Simpson
Nikki Sixx
Nikki Sixx/Tommy Lee/Vince Neil
Nikolai Rimsky-Korsakov
Nirvana
O. Osbourne
O. Osbourne, R. Daisley, R. Rhoads
O. Osbourne, R. Daisley, R. Rhoads, L. Kerslake
Orestes Barbosa-Sílvio Caldas
Os Mutantes - Arnolpho Lima Filho
Page, Jones
Patrick Claher/Richard Bull
Paul Di'Anno/Steve Harris
Paul O'duffy
Paul Stanley

In [ ]:
%%script sqlite3 --column --header chinook.db
SELECT DISTINCT COUNT(composer)
FROM tracks
;

COUNT(composer)
---------------
2525

**Question:** How many artists composed their own music?

In [ ]:
%%script sqlite3 --column --header chinook.db
SELECT *
FROM artists, tracks
WHERE artists.name = tracks.composer
ORDER BY name ASC
;

ArtistId  Name                   TrackId  Name                                                       AlbumId  MediaTypeId  GenreId  Composer               Milliseconds  Bytes     UnitPrice
--------  ---------------------  -------  ---------------------------------------------------------  -------  -----------  -------  ---------------------  ------------  --------  ---------
1         AC/DC                  18       Bad Boy Boogie                                             4        1            1        AC/DC                  267728        8776140   0.99
1         AC/DC                  16       Dog Eat Dog                                                4        1            1        AC/DC                  215196        7032162   0.99
1         AC/DC                  15       Go Down                                                    4        1            1        AC/DC                  331180        10847611  0.99
1         AC/DC                  21       Hell Ain't A Bad Place To Be                               4        1            1        AC/DC                  254380        8331286   0.99
1         AC/DC                  17       Let There Be Rock                                          4        1            1        AC/DC                  366654        12021261  0.99
1         AC/DC                  20       Overdose                                                   4        1            1        AC/DC                  369319        12066294  0.99
1         AC/DC                  19       Problem Child                                              4        1            1        AC/DC                  325041        10617116  0.99
1         AC/DC                  22       Whole Lotta Rosie                                          4        1            1        AC/DC                  323761        10547154  0.99
202       Aaron Goldberg         3357     OAM's Blues                                                267      5            2        Aaron Goldberg         266936        4292028   0.99
7         Apocalyptica           82       Creeping Death                                             9        1            3        Apocalyptica           308035        10110980  0.99
7         Apocalyptica           77       Enter Sandman                                              9        1            3        Apocalyptica           221701        7286305   0.99
7         Apocalyptica           79       Harvester Of Sorrow                                        9        1            3        Apocalyptica           374543        12372536  0.99
7         Apocalyptica           78       Master Of Puppets                                          9        1            3        Apocalyptica           436453        14375310  0.99
7         Apocalyptica           81       Sad But True                                               9        1            3        Apocalyptica           288208        9405526   0.99
7         Apocalyptica           80       The Unforgiven                                             9        1            3        Apocalyptica           322925        10422447  0.99
7         Apocalyptica           84       Welcome Home (Sanitarium)                                  9        1            3        Apocalyptica           350197        11406431  0.99
7         Apocalyptica           83       Wherever I May Roam                                        9        1            3        Apocalyptica           369345        12033110  0.99
10        Billy Cobham           126      Moon germs                                                 13       1            2        Billy Cobham           294060        9714812   0.99
10        Billy Cobham           123      Quadrant                                                   13       1            2        Billy Cobham           261851        8538199   0.99
10        Billy Cobham           124      Snoopy's search-Red baron                                  13       1            2        Billy Cobham           456071        15075616  0.99
10        Billy Cobham           129      Solo-Panhandler                                            13       1            2        Billy Cobham           246151        8230661   0.99
10        Billy Cobham           125      Spanish moss-"A sound portrait"-Spanish moss               13       1            2        Billy Cobham           248084        8217867   0.99
10        Billy Cobham           127      Stratus                                                    13       1            2        Billy Cobham           582086        19115680  0.99
10        Billy Cobham           128      The pleasant pheasant                                      13       1            2        Billy Cobham           318066        10630578  0.99
12        Black Sabbath          410      Sabbra Cadabra                                             35       1            3        Black Sabbath          380342        12418147  0.99
14        Bruce Dickinson        1333     Bring Your Daughter... ...To The Slaughter                 105      1            3        Bruce Dickinson        284238        4548608   0.99
14        Bruce Dickinson        1231     Bring Your Daughter... To The Slaughter                    96       1            3        Bruce Dickinson        317727        5085184   0.99
14        Bruce Dickinson        1336     Revelations                                                106      1            3        Bruce Dickinson        408607        6539264   0.99
15        Buddy Guy              199      Leave My Girl Alone                                        20       1            6        Buddy Guy              204721        6859518   0.99
15        Buddy Guy              200      She Suits Me To A Tee                                      20       1            6        Buddy Guy              136803        4456321   0.99
15        Buddy Guy              196      Stone Crazy                                                20       1            6        Buddy Guy              433397        14184984  0.99
16        Caetano Veloso         220      A Luz De Tieta                                             21       1            7        Caetano Veloso         251742        8507446   0.99
16        Caetano Veloso         383      Ando Meio Desligado                                        33       1            7        Caetano Veloso         195813        6547648   0.99
16        Caetano Veloso         532      Baby                                                       42       1            4        Caetano Veloso         177188        5798202   0.99
16        Caetano Veloso         209      Eclipse Oculto                                             21       1            7        Caetano Veloso         221936        7382703   0.99
16        Caetano Veloso         216      Esse Cara                                                  21       1            7        Caetano Veloso         223111        7217126   0.99
16        Caetano Veloso         382      Menino do Rio                                              33       1            7        Caetano Veloso         262713        8737489   0.99
16        Caetano Veloso         219      Odara                                                      21       1            7        Caetano Veloso         141270        4704104   0.99
16        Caetano Veloso         213      Saudosismo                                                 21       1            7        Caetano Veloso         144326        4726981   0.99
16        Caetano Veloso         208      Terra                                                      21       1            7        Caetano Veloso         482429        15889054  0.99
16        Caetano Veloso         210      Texto "Verdade Tropical"                                   21       1            7        Caetano Veloso         84088         2752161   0.99
17        Chico Buarque          214      Carolina                                                   21       1            7        Chico Buarque          181812        5924159   0.99
205       Chris Cornell          3377     Arms Around Your Love                                      270      2            23       Chris Cornell          214016        3516224   0.99
205       Chris Cornell          2522     Bleed Together                                             203      1            1        Chris Cornell          232202        7597074   0.99
205       Chris Cornell          2520     Blow Up The Outside World                                  203      1            1        Chris Cornell          347898        11379527  0.99
205       Chris Cornell          2519     Burden In My Hand                                          203      1            1        Chris Cornell          292153        9659911   0.99
205       Chris Cornell          3387     Disappearing Act                                           270      2            23       Chris Cornell          273320        4476203   0.99
205       Chris Cornell          2517     Fell On Black Days                                         203      1            1        Chris Cornell          282331        9256082   0.99
205       Chris Cornell          3385     Finally Forever                                            270      2            23       Chris Cornell          217035        3565098   0.99
205       Chris Cornell          3380     Ghosts                                                     270      2            23       Chris Cornell          231547        3799745   0.99
205       Chris Cornell          3381     Killing Birds                                              270      2            23       Chris Cornell          218498        3588776   0.99
205       Chris Cornell          2508     Loud Love                                                  203      1            1        Chris Cornell          297456        9660953   0.99
205       Chris Cornell          3375     No Such Thing                                              270      2            23       Chris Cornell          224837        3691272   0.99
205       Chris Cornell          2512     Outshined                                                  203      1            1        Chris Cornell          312476        10274629  0.99
205       Chris Cornell          3376     Poison Eye                                                 270      2            23       Chris Cornell          237120        3890037   0.99
205       Chris Cornell          2518     Pretty Noose                                               203      1            1        Chris Cornell          253570        8317931   0.99
205       Chris Cornell          2513     Rusty Cage                                                 203      1            1        Chris Cornell          267728        8779485   0.99
205       Chris Cornell          3378     Safe and Sound                                             270      2            23       Chris Cornell          256764        4207769   0.99
205       Chris Cornell          3383     Scar On the Sky                                            270      2            23       Chris Cornell          220193        3616618   0.99
205       Chris Cornell          3379     She'll Never Be Your Man                                   270      2            23       Chris Cornell          204078        3355715   0.99
205       Chris Cornell          3386     Silence the Voices                                         270      2            23       Chris Cornell          267376        4379597   0.99
205       Chris Cornell          2514     Spoonman                                                   203      1            1        Chris Cornell          248476        8289906   0.99
205       Chris Cornell          2515     The Day I Tried To Live                                    203      1            1        Chris Cornell          321175        10507137  0.99
205       Chris Cornell          3388     You Know My Name                                           270      2            23       Chris Cornell          240255        3940651   0.99
205       Chris Cornell          3384     Your Soul Today                                            270      2            23       Chris Cornell          205959        3385722   0.99
19        Cidade Negra           309      Downtown                                                   27       1            8        Cidade Negra           239725        8024386   0.99
55        David Coverdale        492      Don't You Cry                                              40       1            1        David Coverdale        347036        11269612  0.99
55        David Coverdale        489      Into The Light                                             40       1            1        David Coverdale        76303         2452653   0.99
55        David Coverdale        490      River Song                                                 40       1            1        David Coverdale        439510        14359478  0.99
55        David Coverdale        491      She Give Me ...                                            40       1            1        David Coverdale        252551        8385478   0.99
55        David Coverdale        500      Wherever You May Go                                        40       1            1        David Coverdale        239699        7803074   0.99
80        Djavan                 875      Acelerou                                                   70       1            7        Djavan                 284133        9391439   0.99
80        Djavan                 870      Amar É Tudo                                                70       1            7        Djavan                 211617        7073899   0.99
80        Djavan                 871      Azul                                                       70       1            7        Djavan                 253962        8381029   0.99
80        Djavan                 867      Açai                                                       70       1            7        Djavan                 270968        8893682   0.99
80        Djavan                 869      Flor De Lis                                                70       1            7        Djavan                 236355        7801108   0.99
80        Djavan                 865      Nem Um Dia                                                 70       1            7        Djavan                 337423        11181446  0.99
80        Djavan                 866      Oceano                                                     70       1            7        Djavan                 217338        7026441   0.99
80        Djavan                 864      Samurai                                                    70       1            7        Djavan                 330997        10872787  0.99
80        Djavan                 872      Seduzir                                                    70       1            7        Djavan                 277524        9163253   0.99
80        Djavan                 868      Serrado                                                    70       1            7        Djavan                 295314        9842240   0.99
80        Djavan                 874      Sina                                                       70       1            7        Djavan                 268173        8906539   0.99
80        Djavan                 876      Um Amor Puro                                               70       1            7        Djavan                 327105        10664698  0.99
81        Eric Clapton           913      Lonely Stranger                                            73       1            6        Eric Clapton           328724        10894406  0.99
81        Eric Clapton           909      Signe                                                      73       1            6        Eric Clapton           193515        6475042   0.99
82        Faith No More          974      Edge Of The World                                          77       1            4        Faith No More          250357        8235607   0.99
82        Faith No More          965      Epic                                                       77       1            4        Faith No More          294008        9631296   0.99
82        Faith No More          966      Falling To Pieces                                          77       1            4        Faith No More          316055        10333123  0.99
82        Faith No More          964      From Out Of Nowhere                                        77       1            4        Faith No More          202527        6587802   0.99
82        Faith No More          967      Surprise! You're Dead!                                     77       1            4        Faith No More          147226        4823036   0.99
82        Faith No More          971      The Morning After                                          77       1            4        Faith No More          223764        7355898   0.99
82        Faith No More          969      The Real Thing                                             77       1            4        Faith No More          493635        16233080  0.99
82        Faith No More          970      Underwater Love                                            77       1            4        Faith No More          231993        7634387   0.99
82        Faith No More          972      Woodpecker From Mars                                       77       1            4        Faith No More          340532        11174250  0.99
82        Faith No More          968      Zombie Eaters                                              77       1            4        Faith No More          360881        11835367  0.99
84        Foo Fighters           1009     All My Life                                                81       1            4        Foo Fighters           263653        8665545   0.99
84        Foo Fighters           1018     Burn Away                                                  81       1            4        Foo Fighters           298396        9678073   0.99
84        Foo Fighters           1019     Come Back                                                  81       1            4        Foo Fighters           469968        15371980  0.99
84        Foo Fighters           1013     Disenchanted Lullaby                                       81       1            4        Foo Fighters           273528        8919111   0.99
84        Foo Fighters           1015     Halo                                                       81       1            4        Foo Fighters           306442        10026371  0.99
84        Foo Fighters           1011     Have It All                                                81       1            4        Foo Fighters           298057        9729292   0.99
84        Foo Fighters           1016     Lonely As You                                              81       1            4        Foo Fighters           277185        9022628   0.99
84        Foo Fighters           1010     Low                                                        81       1            4        Foo Fighters           268120        8847196   0.99
84        Foo Fighters           1017     Overdrive                                                  81       1            4        Foo Fighters           270550        8793187   0.99
84        Foo Fighters           1012     Times Like These                                           81       1            4        Foo Fighters           266370        8624691   0.99
84        Foo Fighters           1014     Tired Of You                                               81       1            4        Foo Fighters           311353        10094743  0.99

In [ ]:
%%script sqlite3 --column --header chinook.db
WITH legends AS(
  SELECT *
  FROM artists, tracks
  WHERE artists.name = tracks.composer
)
SELECT COUNT(*) AS total_rows
FROM legends
;

total_rows
----------
402

### Aggregates

Let's move on to see if there are any financial trends for performing singer-songwriters, versus those who *didn't*.

We find that there is a relationship between `invoice_items` and `tracks`

#### MAX

In [ ]:
%%script sqlite3 --column --header chinook.db
SELECT *
FROM invoice_items
LIMIT 5
;

InvoiceLineId  InvoiceId  TrackId  UnitPrice  Quantity
-------------  ---------  -------  ---------  --------
1              1          2        0.99       1
2              1          4        0.99       1
3              2          6        0.99       1
4              2          8        0.99       1
5              2          10       0.99       1

**Question:** What is the maximum unit price for a song?

In [ ]:
%%script sqlite3 --column --header chinook.db
SELECT MAX(UnitPrice)
FROM invoice_items
;

MAX(UnitPrice)
--------------
1.99

**Question:** What is the minimum?

In [ ]:
%%script sqlite3 --column --header chinook.db
SELECT MIN(UnitPrice)
FROM invoice_items
;

MIN(UnitPrice)
--------------
0.99

**Question:** How many sales are there total in the `invoice_items`?

In [ ]:
%%script sqlite3 --column --header chinook.db
SELECT SUM(UnitPrice)
FROM invoice_items
;

SUM(UnitPrice)
----------------
2328.59999999996

**Question:** Does this number match the sales in `tracks`?

In [ ]:
%%script sqlite3 --column --header chinook.db
SELECT SUM(UnitPrice)
FROM tracks
;

SUM(UnitPrice)
---------------
3680.9699999997

We find a discrepancy in the sum of `UnitPrice` between both `invoice_items` and `tracks`, likely because one serves as a "source of truth" and the other is a reference.

Let's take a look at the `invoices` table for clues.

In [ ]:
%%script sqlite3 --column --header chinook.db
SELECT *
FROM invoices
;

InvoiceId  CustomerId  InvoiceDate          BillingAddress                            BillingCity          BillingState  BillingCountry  BillingPostalCode  Total
---------  ----------  -------------------  ----------------------------------------  -------------------  ------------  --------------  -----------------  -----
1          2           2009-01-01 00:00:00  Theodor-Heuss-Straße 34                   Stuttgart                          Germany         70174              1.98
2          4           2009-01-02 00:00:00  Ullevålsveien 14                          Oslo                               Norway          0171               3.96
3          8           2009-01-03 00:00:00  Grétrystraat 63                           Brussels                           Belgium         1000               5.94
4          14          2009-01-06 00:00:00  8210 111 ST NW                            Edmonton             AB            Canada          T6G 2C7            8.91
5          23          2009-01-11 00:00:00  69 Salem Street                           Boston               MA            USA             2113               13.86
6          37          2009-01-19 00:00:00  Berger Straße 10                          Frankfurt                          Germany         60316              0.99
7          38          2009-02-01 00:00:00  Barbarossastraße 19                       Berlin                             Germany         10779              1.98
8          40          2009-02-01 00:00:00  8, Rue Hanovre                            Paris                              France          75002              1.98
9          42          2009-02-02 00:00:00  9, Place Louis Barthou                    Bordeaux                           France          33000              3.96
10         46          2009-02-03 00:00:00  3 Chatham Street                          Dublin               Dublin        Ireland                            5.94
11         52          2009-02-06 00:00:00  202 Hoxton Street                         London                             United Kingdom  N1 5LH             8.91
12         2           2009-02-11 00:00:00  Theodor-Heuss-Straße 34                   Stuttgart                          Germany         70174              13.86
13         16          2009-02-19 00:00:00  1600 Amphitheatre Parkway                 Mountain View        CA            USA             94043-1351         0.99
14         17          2009-03-04 00:00:00  1 Microsoft Way                           Redmond              WA            USA             98052-8300         1.98
15         19          2009-03-04 00:00:00  1 Infinite Loop                           Cupertino            CA            USA             95014              1.98
16         21          2009-03-05 00:00:00  801 W 4th Street                          Reno                 NV            USA             89503              3.96
17         25          2009-03-06 00:00:00  319 N. Frances Street                     Madison              WI            USA             53703              5.94
18         31          2009-03-09 00:00:00  194A Chain Lake Drive                     Halifax              NS            Canada          B3S 1C5            8.91
19         40          2009-03-14 00:00:00  8, Rue Hanovre                            Paris                              France          75002              13.86
20         54          2009-03-22 00:00:00  110 Raeburn Pl                            Edinburgh                          United Kingdom  EH4 1HH            0.99
21         55          2009-04-04 00:00:00  421 Bourke Street                         Sidney               NSW           Australia       2010               1.98
22         57          2009-04-04 00:00:00  Calle Lira, 198                           Santiago                           Chile                              1.98
23         59          2009-04-05 00:00:00  3,Raj Bhavan Road                         Bangalore                          India           560001             3.96
24         4           2009-04-06 00:00:00  Ullevålsveien 14                          Oslo                               Norway          0171               5.94
25         10          2009-04-09 00:00:00  Rua Dr. Falcão Filho, 155                 São Paulo            SP            Brazil          01007-010          8.91
26         19          2009-04-14 00:00:00  1 Infinite Loop                           Cupertino            CA            USA             95014              13.86
27         33          2009-04-22 00:00:00  5112 48 Street                            Yellowknife          NT            Canada          X1A 1N6            0.99
28         34          2009-05-05 00:00:00  Rua da Assunção 53                        Lisbon                             Portugal                           1.98
29         36          2009-05-05 00:00:00  Tauentzienstraße 8                        Berlin                             Germany         10789              1.98
30         38          2009-05-06 00:00:00  Barbarossastraße 19                       Berlin                             Germany         10779              3.96
31         42          2009-05-07 00:00:00  9, Place Louis Barthou                    Bordeaux                           France          33000              5.94
32         48          2009-05-10 00:00:00  Lijnbaansgracht 120bg                     Amsterdam            VV            Netherlands     1016               8.91
33         57          2009-05-15 00:00:00  Calle Lira, 198                           Santiago                           Chile                              13.86
34         12          2009-05-23 00:00:00  Praça Pio X, 119                          Rio de Janeiro       RJ            Brazil          20040-020          0.99
35         13          2009-06-05 00:00:00  Qe 7 Bloco G                              Brasília             DF            Brazil          71020-677          1.98
36         15          2009-06-05 00:00:00  700 W Pender Street                       Vancouver            BC            Canada          V6C 1G8            1.98
37         17          2009-06-06 00:00:00  1 Microsoft Way                           Redmond              WA            USA             98052-8300         3.96
38         21          2009-06-07 00:00:00  801 W 4th Street                          Reno                 NV            USA             89503              5.94
39         27          2009-06-10 00:00:00  1033 N Park Ave                           Tucson               AZ            USA             85719              8.91
40         36          2009-06-15 00:00:00  Tauentzienstraße 8                        Berlin                             Germany         10789              13.86
41         50          2009-06-23 00:00:00  C/ San Bernardo 85                        Madrid                             Spain           28015              0.99
42         51          2009-07-06 00:00:00  Celsiusg. 9                               Stockholm                          Sweden          11230              1.98
43         53          2009-07-06 00:00:00  113 Lupus St                              London                             United Kingdom  SW1V 3EN           1.98
44         55          2009-07-07 00:00:00  421 Bourke Street                         Sidney               NSW           Australia       2010               3.96
45         59          2009-07-08 00:00:00  3,Raj Bhavan Road                         Bangalore                          India           560001             5.94
46         6           2009-07-11 00:00:00  Rilská 3174/6                             Prague                             Czech Republic  14300              8.91
47         15          2009-07-16 00:00:00  700 W Pender Street                       Vancouver            BC            Canada          V6C 1G8            13.86
48         29          2009-07-24 00:00:00  796 Dundas Street West                    Toronto              ON            Canada          M6J 1V1            0.99
49         30          2009-08-06 00:00:00  230 Elgin Street                          Ottawa               ON            Canada          K2P 1L7            1.98
50         32          2009-08-06 00:00:00  696 Osborne Street                        Winnipeg             MB            Canada          R3L 2B9            1.98
51         34          2009-08-07 00:00:00  Rua da Assunção 53                        Lisbon                             Portugal                           3.96
52         38          2009-08-08 00:00:00  Barbarossastraße 19                       Berlin                             Germany         10779              5.94
53         44          2009-08-11 00:00:00  Porthaninkatu 9                           Helsinki                           Finland         00530              8.91
54         53          2009-08-16 00:00:00  113 Lupus St                              London                             United Kingdom  SW1V 3EN           13.86
55         8           2009-08-24 00:00:00  Grétrystraat 63                           Brussels                           Belgium         1000               0.99
56         9           2009-09-06 00:00:00  Sønder Boulevard 51                       Copenhagen                         Denmark         1720               1.98
57         11          2009-09-06 00:00:00  Av. Paulista, 2022                        São Paulo            SP            Brazil          01310-200          1.98
58         13          2009-09-07 00:00:00  Qe 7 Bloco G                              Brasília             DF            Brazil          71020-677          3.96
59         17          2009-09-08 00:00:00  1 Microsoft Way                           Redmond              WA            USA             98052-8300         5.94
60         23          2009-09-11 00:00:00  69 Salem Street                           Boston               MA            USA             2113               8.91
61         32          2009-09-16 00:00:00  696 Osborne Street                        Winnipeg             MB            Canada          R3L 2B9            13.86
62         46          2009-09-24 00:00:00  3 Chatham Street                          Dublin               Dublin        Ireland                            0.99
63         47          2009-10-07 00:00:00  Via Degli Scipioni, 43                    Rome                 RM            Italy           00192              1.98
64         49          2009-10-07 00:00:00  Ordynacka 10                              Warsaw                             Poland          00-358             1.98
65         51          2009-10-08 00:00:00  Celsiusg. 9                               Stockholm                          Sweden          11230              3.96
66         55          2009-10-09 00:00:00  421 Bourke Street                         Sidney               NSW           Australia       2010               5.94
67         2           2009-10-12 00:00:00  Theodor-Heuss-Straße 34                   Stuttgart                          Germany         70174              8.91
68         11          2009-10-17 00:00:00  Av. Paulista, 2022                        São Paulo            SP            Brazil          01310-200          13.86
69         25          2009-10-25 00:00:00  319 N. Frances Street                     Madison              WI            USA             53703              0.99
70         26          2009-11-07 00:00:00  2211 W Berry Street                       Fort Worth           TX            USA             76110              1.98
71         28          2009-11-07 00:00:00  302 S 700 E                               Salt Lake City       UT            USA             84102              1.98
72         30          2009-11-08 00:00:00  230 Elgin Street                          Ottawa               ON            Canada          K2P 1L7            3.96
73         34          2009-11-09 00:00:00  Rua da Assunção 53                        Lisbon                             Portugal                           5.94
74         40          2009-11-12 00:00:00  8, Rue Hanovre                            Paris                              France          75002              8.91
75         49          2009-11-17 00:00:00  Ordynacka 10                              Warsaw                             Poland          00-358             13.86
76         4           2009-11-25 00:00:00  Ullevålsveien 14                          Oslo                               Norway          0171               0.99
77         5           2009-12-08 00:00:00  Klanova 9/506                             Prague                             Czech Republic  14700              1.98
78         7           2009-12-08 00:00:00  Rotenturmstraße 4, 1010 Innere Stadt      Vienne                             Austria         1010               1.98
79         9           2009-12-09 00:00:00  Sønder Boulevard 51                       Copenhagen                         Denmark         1720               3.96
80         13          2009-12-10 00:00:00  Qe 7 Bloco G                              Brasília             DF            Brazil          71020-677          5.94
81         19          2009-12-13 00:00:00  1 Infinite Loop                           Cupertino            CA            USA             95014              8.91
82         28          2009-12-18 00:00:00  302 S 700 E                               Salt Lake City       UT            USA             84102              13.86
83         42          2009-12-26 00:00:00  9, Place Louis Barthou                    Bordeaux                           France          33000              0.99
84         43          2010-01-08 00:00:00  68, Rue Jouvence                          Dijon                              France          21000              1.98
85         45          2010-01-08 00:00:00  Erzsébet krt. 58.                         Budapest                           Hungary         H-1073             1.98
86         47          2010-01-09 00:00:00  Via Degli Scipioni, 43                    Rome                 RM            Italy           00192              3.96
87         51          2010-01-10 00:00:00  Celsiusg. 9                               Stockholm                          Sweden          11230              6.94
88         57          2010-01-13 00:00:00  Calle Lira, 198                           Santiago                           Chile                              17.91
89         7           2010-01-18 00:00:00  Rotenturmstraße 4, 1010 Innere Stadt      Vienne                             Austria         1010               18.86
90         21          2010-01-26 00:00:00  801 W 4th Street                          Reno                 NV            USA             89503              0.99
91         22          2010-02-08 00:00:00  120 S Orange Ave                          Orlando              FL            USA             32801              1.98
92         24          2010-02-08 00:00:00  162 E Superior Street                     Chicago              IL            USA             60611              1.98
93         26          2010-02-09 00:00:00  2211 W Berry Street                       Fort Worth           TX            USA             76110              3.96
94         30          2010-02-10 00:00:00  230 Elgin Street                          Ottawa               ON            Canada          K2P 1L7            5.94
95         36          2010-02-13 00:00:00  Tauentzienstraße 8                        Berlin                             Germany         10789              8.91
96         45          2010-02-18 00:00:00  Erzsébet krt. 58.                         Budapest                           Hungary         H-1073             21.86
97         59          2010-02-26 00:00:00  3,Raj Bhavan Road                         Bangalore                          India           560001             1.99
98         1           2010-03-11 00:00:00  Av. Brigadeiro Faria Lima, 2170           São José dos Campos  SP            Brazil          12227-000          3.98
99         3           2010-03-11 00:00:00  1498 rue Bélanger                         Montréal             QC            Canada          H2G 1A7            3.98
100        5           2010-03-12 00:00:00  Klanova 9/506                             Prague                             Czech Republic  14700              3.96
101        9           2010-03-13 00:00:00  Sønder Boulevard 51                       Copenhagen                         Denmark         1720               5.94
102        15          2010-03-16 00:00:00  700 W Pender Street                       Vancouver            BC            Canada          V6C 1G8            9.91
103        24          2010-03-21 00:00:00  162 E Superior Street                     Chicago              IL            USA             60611              15.86
104        38          2010-03-29 00:00:00  Barbarossastraße 19                       Berlin                             Germany         10779              0.99
105        39          2010-04-11 00:00:00  4, Rue Milton                             Paris                              France          75009              1.98
106        41          2010-04-11 00:00:00  11, Place Bellecour                       Lyon                               France          69002              1.98
107        43          2010-04-12 00:00:00  68, Rue Jouvence                          Dijon                              France          21000              3.96
108        47          2010-04-13 00:00:00  Via Degli Scipioni, 43                    Rome                 RM            Italy           00192              5.94
109        53          2010-04-16 00:00:00  113 Lupus St                              London                             United Kingdom  SW1V 3EN           8.91
110        3           2010-04-21 00:00:00  1498 rue Bélanger                         Montréal             QC            Canada          H2G 1A7            13.86
111        17          2010-04-29 00:00:00  1 Microsoft Way                           Redmond              WA            USA             98052-8300         0.99
112        18          2010-05-12 00:00:00  627 Broadway                              New York             NY            USA             10012-2612         1.98
113        20          2010-05-12 00:00:00  541 Del Medio Avenue                      Mountain View        CA            USA             94040-111          1.98
114        22          2010-05-13 00:00:00  120 S Orange Ave                          Orlando              FL            USA             32801              3.96
115        26          2010-05-14 00:00:00  2211 W Berry Street                       Fort Worth           TX            USA             76110              5.94
116        32          2010-05-17 00:00:00  696 Osborne Street                        Winnipeg             MB            Canada          R3L 2B9            8.91
117        41          2010-05-22 00:00:00  11, Place Bellecour                       Lyon                               France          69002              13.86
118        55          2010-05-30 00:00:00  421 Bourke Street                         Sidney               NSW           Australia       2010               0.99
119        56          2010-06-12 00:00:00  307 Macacha Güemes                        Buenos Aires                       Argentina       1106               1.98
120        58          2010-06-12 00:00:00  12,Community Centre                       Delhi                              India           110017             1.98
121        1           2010-06-13 00:00:00  Av. Brigadeiro Faria Lima, 2170           São José dos Campos  SP            Brazil          12227-000          3.96
122        5           2010-06-14 00:00:00  Klanova 9/506                             Prague                             Czech Republic  14700              5.94

**Question:** What is the total sales amount by media type?

In [ ]:
%%script sqlite3 --column --header chinook.db
SELECT
    tracks.MediaTypeId,
    SUM(invoice_items.UnitPrice * invoice_items.Quantity) AS total_sales
FROM invoice_items
JOIN tracks ON invoice_items.TrackId = tracks.TrackId
GROUP BY tracks.MediaTypeId
ORDER BY total_sales DESC
;

MediaTypeId  total_sales
-----------  ----------------
1            1956.24000000002
3            220.89
2            144.54
4            3.96
5            2.97

As expected, we find that the most sales went toward the popular "MPEG audio file." Let's plot this.

In [ ]:
# store query as a variable
query = """
SELECT
    tracks.MediaTypeId,
    SUM(invoice_items.UnitPrice * invoice_items.Quantity) AS total_sales
FROM invoice_items
JOIN tracks ON invoice_items.TrackId = tracks.TrackId
GROUP BY tracks.MediaTypeId
ORDER BY total_sales DESC
;
"""

# assign to call later
media_type_sales = pd.read_sql_query( query, db_con )
media_type_sales

   MediaTypeId  total_sales
0            1      1956.24
1            3       220.89
2            2       144.54
3            4         3.96
4            5         2.97

In [ ]:
%%script sqlite3 --column --header chinook.db
SELECT *
FROM media_types
LIMIT 10
;

MediaTypeId  Name
-----------  ---------------------------
1            MPEG audio file
2            Protected AAC audio file
3            Protected MPEG-4 video file
4            Purchased AAC audio file
5            AAC audio file

In [ ]:
# add new col with readable labels
media_type_sales["media_names"] = [
    "MPEG audio file",
    "Protected AAC audio file",
    "Protected MPEG-4 video file",
    "Purchased AAC audio file",
    "AAC audio file"]

media_type_sales["media_shorthand"] = [
    "MPEG",
    "*AAC",
    "*MPEG-4",
    "Purchased AAC",
    "AAC"]

media_type_sales

   MediaTypeId  total_sales                  media_names media_shorthand
0            1      1956.24              MPEG audio file            MPEG
1            3       220.89     Protected AAC audio file            *AAC
2            2       144.54  Protected MPEG-4 video file         *MPEG-4
3            4         3.96     Purchased AAC audio file   Purchased AAC
4            5         2.97               AAC audio file             AAC

In [ ]:
import plotly.express as px

fig = px.bar(media_type_sales,
             x = "media_shorthand",
             y = "total_sales",
             text_auto = ".2s",
             title = "Chinook Total Sales by Media Type",
             labels={'media_shorthand': 'Media Type (*denotes protected file)',
                     'total_sales': 'Total Sales ($)'})
fig.show()

### 👩🏼‍💻 Future Development
* Clean the "Artist" and "Composer" fields for more accurate matching.
* Investigate which performing singer-songwriters made the most money.